# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
#sudo: false
cache: packages
warnings_are_errors: false

after_success:
    - Rscript -e 'library(covr); codecov()'
email:
    recipients:
      - jessicaleighburnett@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

# environment variables set for all builds
env:
  global:
    - BIOC_USE_DEVEL="FALSE"  ## Use the current release version
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions

# for codecov, testing
r_packages:
  - covr
  - testthat

after_success:
  - Rscript -e 'library(covr); codecov()'
  - travis_wait 20 Rscript -e 'library(covr); codecov()'

