# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
#sudo: false
cache: packages
warnings_are_errors: false

after_success:
    - Rscript -e 'library(covr); codecov()'
email:
    recipients:
      - jessicaleighburnett@gmail.com
    on_success: never # default: change
    on_failure: always # default: always


r_build_args: '--no-build-vignettes --no-manual'
r_check_args: '--ignore-vignettes --no-manual'


# for codecov, testing
r_packages:
  - covr
  - testthat

after_success:
  - Rscript -e 'library(covr); codecov()'
  - travis_wait 20 Rscript -e 'library(covr); codecov()'

