
## Parsing the complex XML data associated with the more recent BBS data releases is proving not worth the time, right now.
## Until I get some help making the region_codes import automatic, we are doing it by hand.
## This is the script for automating the creation of the dataset using

## Not sure why but when this code to produce region_codes runs during cmd check it fails.
## Therefore, will silence the code here and require user to re-run when updates necessary.... ugh.

## BBS codes (edited by JLB)
# {bbs_codes <- structure(list(CountryNum = c(484, 484, 484, 484, 484, 484, 484,
#                                               484, 484, 484, 484, 484, 484, 484, 484, 484, 484, 484, 484, 484,
#                                               484, 484, 484, 484, 484, 484, 484, 484, 484, 484, 484, 484, 484,
#                                               840, 840, 124, 840, 840, 124, 840, 840, 840, 840, 840, 840, 840,
#                                               840, 840, 840, 840, 840, 840, 840, 840, 124, 840, 840, 840, 840,
#                                               840, 840, 840, 840, 840, 124, 840, 840, 840, 840, 124, 840, 840,
#                                               124, 124, 124, 840, 840, 124, 840, 840, 124, 840, 124, 840, 124,
#                                               840, 840, 840, 840, 840, 840, 840, 840, 840, 840, 840, 124),
#                                StateNum = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
#                                             15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
#                                             30, 31, 32, 48, 2, 3, 4, 6, 7, 11, 14, 17, 18, 21, 22, 25,
#                                             27, 33, 34, 35, 36, 38, 39, 42, 44, 45, 46, 47, 49, 50, 51,
#                                             52, 53, 54, 55, 56, 58, 59, 60, 61, 57, 63, 64, 43, 65, 62,
#                                             66, 67, 68, 69, 72, 75, 74, 76, 77, 79, 80, 81, 82, 83, 85,
#                                             87, 88, 89, 90, 91, 92, 93), State = c("Aguascalientes",
#                                                                                    "Baja California", "Baja California Sur", "Campeche", "Chiapas",
#                                                                                    "Chihuahua", "Coahuila", "Colima", "Mexico City", "Durango",
#                                                                                    "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "México",
#                                                                                    "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca",
#                                                                                    "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí",
#                                                                                    "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala",
#                                                                                    "Veracruz", "Yucatán", "Zacatecas", "México Country", "ALABAMA",
#                                                                                    "ALASKA", "Alberta", "ARIZONA", "ARKANSAS", "British Columbia",
#                                                                                    "CALIFORNIA", "COLORADO", "CONNECTICUT", "DELAWARE", "District of Columbia",
#                                                                                    "FLORIDA", "GEORGIA", "IDAHO", "ILLINOIS", "INDIANA", "IOWA",
#                                                                                    "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", "Manitoba", "MARYLAND",
#                                                                                    "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSISSIPPI",
#                                                                                    "MISSOURI", "MONTANA", "NEBRASKA", "NEVADA", "New Brunswick",
#                                                                                    "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NEW YORK",
#                                                                                    "Newfoundland and Labrador", "NORTH CAROLINA", "NORTH DAKOTA",
#                                                                                    "Northwest Territories", "Nova Scotia", "Nunavut", "OHIO",
#                                                                                    "OKLAHOMA", "Ontario", "OREGON", "PENNSYLVANIA", "Prince Edward Island",
#                                                                                    "PUERTO RICO", "Quebec", "RHODE ISLAND", "Saskatchewan",
#                                                                                    "SOUTH CAROLINA", "SOUTH DAKOTA", "TENNESSEE", "TEXAS", "UTAH",
#                                                                                    "VERMONT", "VIRGINIA", "WASHINGTON", "WEST VIRGINIA", "WISCONSIN",
#                                                                                    "WYOMING", "Yukon"), zip_states = c(NA, NA, NA, NA, NA, NA,
#                                                                                                                        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
#                                                                                                                        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "Alabama.zip",
#                                                                                                                        "Alaska.zip", "Alberta.zip", "Arizona.zip", "Arkansa.zip",
#                                                                                                                        "BritCol.zip", "Califor.zip", "Colorad.zip", "Connect.zip",
#                                                                                                                        "Delawar.zip", NA, "Florida.zip", "Georgia.zip", "Idaho.zip",
#                                                                                                                        "Illinoi.zip", "Indiana.zip", "Iowa.zip", "Kansas.zip", "Kentuck.zip",
#                                                                                                                        "Louisia.zip", "Maine.zip", "Manitob.zip", "Marylan.zip",
#                                                                                                                        "Massach.zip", "Michiga.zip", "Minneso.zip", "Mississ.zip",
#                                                                                                                        "Missour.zip", "Montana.zip", "Nebrask.zip", "Nevada.zip",
#                                                                                                                        "NBrunsw.zip", "NHampsh.zip", "NJersey.zip", "NMexico.zip",
#                                                                                                                        "NYork.zip", "Newfoun.zip", "NCaroli.zip", "NDakota.zip",
#                                                                                                                        "NWTerri.zip", "NovaSco.zip", "Nunavut.zip", "Ohio.zip",
#                                                                                                                        "Oklahom.zip", "Ontario.zip", "Oregon.zip", "Pennsyl.zip",
#                                                                                                                        "PEI.zip", NA, "Quebec.zip", "RhodeIs.zip", "SCaroli.zip",
#                                                                                                                        "SDakota.zip", "Saskatc.zip", "Tenness.zip", "Texas.zip",
#                                                                                                                        "Utah.zip", "Vermont.zip", "Virgini.zip", "W_Virgi.zip",
#                                                                                                                        "Washing.zip", "Wiscons.zip", "Wyoming.zip", "Yukon.zip")), row.names = c(NA,
#                                                                                                                                                                                                  -97L), class = "data.frame")
#
# }
#
# bbs_codes <-
#   bbs_codes %>%
#   dplyr::mutate(
#     CountryNum = as.integer(CountryNum),
#     StateNum   = as.integer(StateNum)
#   ) %>%
#   dplyr::select(-zip_states) %>%
#   ## Remove Mexico Country -- not sure what this is.
#   dplyr::filter(tolower(State) != "méxico country") %>%
#   dplyr::mutate(State=tolower(State))
#
# ## ISO CODES
# iso.codes <- rnaturalearth::ne_states() %>%
#   as.data.frame() %>%
#   # tibble::column_to_rownames(name_en) %>%
#   dplyr::select(name_en, iso_3166_2, iso_a2, name_fr, name_es) %>%
#   dplyr::mutate(name_en=tolower(name_en))
#
# # need to SLIGHTLY munge the ISO code name_en to match BBS
# iso.codes$name_en[which(iso.codes$iso_3166_2=="US-DC")] <- "district of columbia"
# iso.codes <- iso.codes %>% dplyr::rename(State=name_en)
#
# ### TEST
# # stopifnot(all(bbs_codes$State %in% iso.codes$name_en))
#
# # Merge Lookup Tables
# region_codes <- dplyr::left_join(bbs_codes, iso.codes)
###The following table was produced using the code above...
region_codes <-
  structure(
    list(
      CountryNum = c(
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        484L,
        840L,
        840L,
        124L,
        840L,
        840L,
        124L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        124L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        124L,
        840L,
        840L,
        840L,
        840L,
        124L,
        840L,
        840L,
        124L,
        124L,
        124L,
        840L,
        840L,
        124L,
        840L,
        840L,
        124L,
        840L,
        124L,
        840L,
        124L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        840L,
        124L
      ),
      StateNum = c(
        1L,
        2L,
        3L,
        4L,
        5L,
        6L,
        7L,
        8L,
        9L,
        10L,
        11L,
        12L,
        13L,
        14L,
        15L,
        16L,
        17L,
        18L,
        19L,
        20L,
        21L,
        22L,
        23L,
        24L,
        25L,
        26L,
        27L,
        28L,
        29L,
        30L,
        31L,
        32L,
        2L,
        3L,
        4L,
        6L,
        7L,
        11L,
        14L,
        17L,
        18L,
        21L,
        22L,
        25L,
        27L,
        33L,
        34L,
        35L,
        36L,
        38L,
        39L,
        42L,
        44L,
        45L,
        46L,
        47L,
        49L,
        50L,
        51L,
        52L,
        53L,
        54L,
        55L,
        56L,
        58L,
        59L,
        60L,
        61L,
        57L,
        63L,
        64L,
        43L,
        65L,
        62L,
        66L,
        67L,
        68L,
        69L,
        72L,
        75L,
        74L,
        76L,
        77L,
        79L,
        80L,
        81L,
        82L,
        83L,
        85L,
        87L,
        88L,
        89L,
        90L,
        91L,
        92L,
        93L
      ),
      State = c(
        "aguascalientes",
        "baja california",
        "baja california sur",
        "campeche",
        "chiapas",
        "chihuahua",
        "coahuila",
        "colima",
        "mexico city",
        "durango",
        "guanajuato",
        "guerrero",
        "hidalgo",
        "jalisco",
        "méxico",
        "michoacán",
        "morelos",
        "nayarit",
        "nuevo león",
        "oaxaca",
        "puebla",
        "querétaro",
        "quintana roo",
        "san luis potosí",
        "sinaloa",
        "sonora",
        "tabasco",
        "tamaulipas",
        "tlaxcala",
        "veracruz",
        "yucatán",
        "zacatecas",
        "alabama",
        "alaska",
        "alberta",
        "arizona",
        "arkansas",
        "british columbia",
        "california",
        "colorado",
        "connecticut",
        "delaware",
        "district of columbia",
        "florida",
        "georgia",
        "idaho",
        "illinois",
        "indiana",
        "iowa",
        "kansas",
        "kentucky",
        "louisiana",
        "maine",
        "manitoba",
        "maryland",
        "massachusetts",
        "michigan",
        "minnesota",
        "mississippi",
        "missouri",
        "montana",
        "nebraska",
        "nevada",
        "new brunswick",
        "new hampshire",
        "new jersey",
        "new mexico",
        "new york",
        "newfoundland and labrador",
        "north carolina",
        "north dakota",
        "northwest territories",
        "nova scotia",
        "nunavut",
        "ohio",
        "oklahoma",
        "ontario",
        "oregon",
        "pennsylvania",
        "prince edward island",
        "puerto rico",
        "quebec",
        "rhode island",
        "saskatchewan",
        "south carolina",
        "south dakota",
        "tennessee",
        "texas",
        "utah",
        "vermont",
        "virginia",
        "washington",
        "west virginia",
        "wisconsin",
        "wyoming",
        "yukon"
      ),
      iso_3166_2 = c(
        "MX-AGU",
        "MX-BCN",
        "MX-BCS",
        "MX-CAM",
        "MX-CHP",
        "MX-CHH",
        "MX-COA",
        "MX-COL",
        "MX-DIF",
        "MX-DUR",
        "MX-GUA",
        "MX-GRO",
        "MX-HID",
        "MX-JAL",
        "MX-MEX",
        "MX-MIC",
        "MX-MOR",
        "MX-NAY",
        "MX-NLE",
        "MX-OAX",
        "MX-PUE",
        "MX-QUE",
        "MX-ROO",
        "MX-SLP",
        "MX-SIN",
        "MX-SON",
        "MX-TAB",
        "MX-TAM",
        "MX-TLA",
        "MX-VER",
        "MX-YUC",
        "MX-ZAC",
        "US-AL",
        "US-AK",
        "CA-AB",
        "US-AZ",
        "US-AR",
        "CA-BC",
        "US-CA",
        "US-CO",
        "US-CT",
        "US-DE",
        "US-DC",
        "US-FL",
        "US-GA",
        "US-ID",
        "US-IL",
        "US-IN",
        "US-IA",
        "US-KS",
        "US-KY",
        "US-LA",
        "US-ME",
        "CA-MB",
        "US-MD",
        "US-MA",
        "US-MI",
        "US-MN",
        "US-MS",
        "US-MO",
        "US-MT",
        "US-NE",
        "US-NV",
        "CA-NB",
        "US-NH",
        "US-NJ",
        "US-NM",
        "US-NY",
        "CA-NL",
        "US-NC",
        "US-ND",
        "CA-NT",
        "CA-NS",
        "CA-NU",
        "US-OH",
        "US-OK",
        "CA-ON",
        "US-OR",
        "US-PA",
        "CA-PE",
        "US-PR",
        "CA-QC",
        "US-RI",
        "CA-SK",
        "US-SC",
        "US-SD",
        "US-TN",
        "US-TX",
        "US-UT",
        "US-VT",
        "US-VA",
        "US-WA",
        "US-WV",
        "US-WI",
        "US-WY",
        "CA-YT"
      ),
      iso_a2 = c(
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "MX",
        "US",
        "US",
        "CA",
        "US",
        "US",
        "CA",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "CA",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "CA",
        "US",
        "US",
        "US",
        "US",
        "CA",
        "US",
        "US",
        "CA",
        "CA",
        "CA",
        "US",
        "US",
        "CA",
        "US",
        "US",
        "CA",
        "PR",
        "CA",
        "US",
        "CA",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "US",
        "CA"
      ),
      name_fr = c(
        "Aguascalientes",
        "Basse-Californie",
        "Basse-Californie du Sud",
        "Campeche",
        "Chiapas",
        "Chihuahua",
        "Coahuila",
        "Colima",
        "Mexico",
        "Durango",
        "Guanajuato",
        "Guerrero",
        "Hidalgo",
        "Jalisco",
        "État de Mexico",
        "Michoacán",
        "Morelos",
        "Nayarit",
        "Nuevo León",
        "Oaxaca",
        "Puebla",
        "Querétaro",
        "Quintana Roo",
        "San Luis Potosí",
        "Sinaloa",
        "Sonora",
        "Tabasco",
        "Tamaulipas",
        "Tlaxcala",
        "Veracruz",
        "Yucatán",
        "Zacatecas",
        "Alabama",
        "Alaska",
        "Alberta",
        "Arizona",
        "Arkansas",
        "Colombie-Britannique",
        "Californie",
        "Colorado",
        "Connecticut",
        "Delaware",
        "Washington",
        "Floride",
        "Géorgie",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiane",
        "Maine",
        "Manitoba",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "Nouveau-Brunswick",
        "New Hampshire",
        "New Jersey",
        "Nouveau-Mexique",
        "État de New York",
        "Terre-Neuve-et-Labrador",
        "Caroline du Nord",
        "Dakota du Nord",
        "Territoires du Nord-Ouest",
        "Nouvelle-Écosse",
        "Nunavut",
        "Ohio",
        "Oklahoma",
        "Ontario",
        "Oregon",
        "Pennsylvanie",
        "Île-du-Prince-Édouard",
        "Porto Rico",
        "Québec",
        "Rhode Island",
        "Saskatchewan",
        "Caroline du Sud",
        "Dakota du Sud",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginie",
        "État de Washington",
        "Virginie-Occidentale",
        "Wisconsin",
        "Wyoming",
        "Yukon"
      ),
      name_es = c(
        "Aguascalientes",
        "Baja California",
        "Baja California Sur",
        "Campeche",
        "Chiapas",
        "Chihuahua",
        "Coahuila de Zaragoza",
        "Colima",
        "Ciudad de México",
        "Durango",
        "Guanajuato",
        "Estado de Guerrero",
        "Estado de Hidalgo",
        "Jalisco",
        "Estado de México",
        "Michoacán",
        "Morelos",
        "Nayarit",
        "Nuevo León",
        "Oaxaca",
        "Puebla",
        "Querétaro",
        "Quintana Roo",
        "San Luis Potosí",
        "Sinaloa",
        "Sonora",
        "Tabasco",
        "Tamaulipas",
        "Tlaxcala",
        "Veracruz",
        "Yucatán",
        "Zacatecas",
        "Alabama",
        "Alaska",
        "Alberta",
        "Arizona",
        "Arkansas",
        "Columbia Británica",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "Washington D. C.",
        "Florida",
        "Georgia",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Luisiana",
        "Maine",
        "Manitoba",
        "Maryland",
        "Massachusetts",
        "Míchigan",
        "Minnesota",
        "Misisipi",
        "Misuri",
        "Montana",
        "Nebraska",
        "Nevada",
        "Nuevo Brunswick",
        "Nuevo Hampshire",
        "Nueva Jersey",
        "Nuevo México",
        "Nueva York",
        "Terranova y Labrador",
        "Carolina del Norte",
        "Dakota del Norte",
        "Territorios del Noroeste",
        "Nueva Escocia",
        "Nunavut",
        "Ohio",
        "Oklahoma",
        "Ontario",
        "Oregón",
        "Pensilvania",
        "Isla del Príncipe Eduardo",
        "Puerto Rico",
        "Quebec",
        "Rhode Island",
        "Saskatchewan",
        "Carolina del Sur",
        "Dakota del Sur",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "Virginia Occidental",
        "Wisconsin",
        "Wyoming",
        "Yukón"
      )
    ),
    row.names = c(NA,-96L),
    class = "data.frame"
  )
# Write the data to package files as .RDA

usethis::use_data(region_codes, overwrite = TRUE)



